# Generated by Django 4.2.5 on 2024-01-09 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('num_of_likes', models.IntegerField(default=0)),
                ('num_of_qustions', models.IntegerField(default=0)),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('project_published', models.BooleanField(default=False)),
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('quiz_published', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
                ('option_1', models.CharField(max_length=150)),
                ('option_2', models.CharField(max_length=150)),
                ('option_3', models.CharField(max_length=150)),
                ('question_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='staff.project')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_like', to='staff.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
